(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.IeumAnalysisCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const data=typeof module==='object'&&module.exports?require('./supabase/functions/analyze-class/relationship-data.js'):globalThis.IeumRelationshipData;
  const monthOf=item=>String(item.survey_month||item.payload_json?.surveyMonth||item.submitted_at||'').slice(0,7);
  const payloadOf=item=>item.payload_json||item.payload||item;
  function latestByStudentMonth(responses){return data.latestRows(responses)}
  function cumulativeScores(responses,students){const latest=latestByStudentMonth(data.normalizeResponses(responses,students)),samples=new Map(),participants=new Set(),relationResponders=new Set(),months=new Set();latest.forEach((item,key)=>{const[,raterText]=key.split(':'),rater=Number(raterText),relationships=payloadOf(item).relationships||[];participants.add(rater);months.add(monthOf(item));if(relationships.length)relationResponders.add(rater);relationships.forEach(row=>{const target=Number(row.targetNumber),score=Number(row.score),pair=`${rater}:${target}`;if(!samples.has(pair))samples.set(pair,[]);samples.get(pair).push(score)})});const scores=new Map([...samples].map(([key,values])=>[key,values.reduce((sum,value)=>sum+value,0)/values.length]));return{latest,samples,scores,participants,relationResponders,months:[...months].sort()}}
  function isRelationshipReady(total,participants,relationResponders){return total>0&&participants/total>=.8&&relationResponders/total>=.8}
  function polarization(values){if(values.length<4)return null;const low=values.filter(value=>value<=2).length,high=values.filter(value=>value>=4).length,average=values.reduce((sum,value)=>sum+value,0)/values.length,sd=Math.sqrt(values.reduce((sum,value)=>sum+(value-average)**2,0)/values.length);return{average,sd,lowRate:low/values.length,highRate:high/values.length,candidate:low>0&&high>0&&sd>=1.2}}
  return{latestByStudentMonth,cumulativeScores,isRelationshipReady,polarization};
});
