(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.IeumAnalysisCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const monthOf=item=>String(item.survey_month||item.payload_json?.surveyMonth||item.submitted_at||'').slice(0,7);
  const payloadOf=item=>item.payload_json||item.payload||item;
  function latestByStudentMonth(responses){const latest=new Map();responses.filter(item=>!item.analysis_excluded).sort((a,b)=>new Date(b.submitted_at||0)-new Date(a.submitted_at||0)).forEach(item=>{const number=Number(item.student_number||payloadOf(item).studentNumber),key=`${monthOf(item)}:${number}`;if(number&&!latest.has(key))latest.set(key,item)});return latest}
  function cumulativeScores(responses){const latest=latestByStudentMonth(responses),samples=new Map(),participants=new Set(),relationResponders=new Set(),months=new Set();latest.forEach((item,key)=>{const[,raterText]=key.split(':'),rater=Number(raterText),relationships=payloadOf(item).relationships||[];participants.add(rater);months.add(monthOf(item));if(relationships.length)relationResponders.add(rater);relationships.forEach(row=>{const target=Number(row.targetNumber),score=Number(row.score),pair=`${rater}:${target}`;if(!target||!Number.isFinite(score))return;if(!samples.has(pair))samples.set(pair,[]);samples.get(pair).push(score)})});const scores=new Map([...samples].map(([key,values])=>[key,values.reduce((sum,value)=>sum+value,0)/values.length]));return{latest,samples,scores,participants,relationResponders,months:[...months].sort()}}
  function isRelationshipReady(total,participants,relationResponders){return total>0&&participants/total>=.8&&relationResponders/total>=.8}
  function polarization(values){if(values.length<4)return null;const low=values.filter(value=>value<=2).length,high=values.filter(value=>value>=4).length,average=values.reduce((sum,value)=>sum+value,0)/values.length,sd=Math.sqrt(values.reduce((sum,value)=>sum+(value-average)**2,0)/values.length);return{average,sd,lowRate:low/values.length,highRate:high/values.length,candidate:low>0&&high>0&&sd>=1.2}}
  return{latestByStudentMonth,cumulativeScores,isRelationshipReady,polarization};
});
