let signals=[];
let allResponses=[];
let selectedAnalysisMonth='';
const defaultStudentNames=['김하린','박도윤','이서준','최유나','정민재','윤서아','한지우','강민준','송지민','임다온','오시우','신예린','조하준','권나윤','안지호','문서윤','장도현','배유진','백시온','류아린','차민서','남도하','유준서','서하은','진우성','표가은','노현우','마지안'];
const defaultSettings={teacherName:'홍현진',schoolYear:2026,grade:5,classNumber:2,classId:'2026-5-2',teacherSecret:'',students:defaultStudentNames.map((name,index)=>({number:index+1,name,accessCode:String(731204+index*7919).slice(-6)}))};
let classSettings=loadClassSettings();
const pageTitles={home:'안녕하세요, 선생님',survey:'설문 관리',analysis:'분석 대시보드',relations:'관계 분석',observations:'관찰 기록',settings:'학급 설정'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function payloadOf(item){let payload=item?.payload_json||item||{};try{if(typeof payload==='string')payload=JSON.parse(payload)}catch(error){return{}}return payload||{}}
function monthOf(item){return String(item?.survey_month||payloadOf(item).surveyMonth||item?.submitted_at||'').slice(0,7)}
function previousMonth(month){const [year,value]=month.split('-').map(Number);const date=new Date(Date.UTC(year,value-2,1));return date.toISOString().slice(0,7)}
function monthLabel(month){if(!/^\d{4}-\d{2}$/.test(month))return month;const [year,value]=month.split('-');return `${year}년 ${Number(value)}월`}
function latestByStudent(responses,month){const latest=new Map();responses.filter(item=>monthOf(item)===month).sort((a,b)=>new Date(b.submitted_at||payloadOf(b).submittedAt||0)-new Date(a.submitted_at||payloadOf(a).submittedAt||0)).forEach(item=>{const number=Number(item.student_number||payloadOf(item).studentNumber);if(number&&!latest.has(number))latest.set(number,item)});return latest}
function quoted(value,max=180){const text=String(value||'').trim();return text?`“${text.length>max?`${text.slice(0,max)}…`:text}”`:''}
function signalTag(type){return type==='urgent'?'즉시 확인':type==='week'?'이번 주 확인':'지속 관찰'}
function standardDeviation(values){if(!values.length)return 0;const average=values.reduce((sum,value)=>sum+value,0)/values.length;return Math.sqrt(values.reduce((sum,value)=>sum+(value-average)**2,0)/values.length)}
function updateMonthSelector(){const months=[...new Set(allResponses.map(monthOf).filter(month=>/^\d{4}-\d{2}$/.test(month)))].sort().reverse();if(!months.length)months.push(new Date().toISOString().slice(0,7));if(!months.includes(selectedAnalysisMonth))selectedAnalysisMonth=months[0];const options=months.map(month=>`<option value="${month}" ${month===selectedAnalysisMonth?'selected':''}>${monthLabel(month)}</option>`).join('');['#analysisMonth','#surveyMonth'].forEach(id=>{const selector=$(id);if(selector)selector.innerHTML=options})}
function analyzeResponses(responses,month){
  const current=latestByStudent(responses,month);const previous=latestByStudent(responses,previousMonth(month));const found=[];let id=1;
  const add=(type,item,title,summary,evidence,hypotheses,observation)=>found.push({id:id++,type,tag:signalTag(type),name:item?.student_name||payloadOf(item).studentName||'학생',studentNumber:Number(item?.student_number||payloadOf(item).studentNumber)||null,submittedAt:item?.submitted_at||payloadOf(item).submittedAt||null,title,summary,evidence:evidence.filter(Boolean),hypotheses,observation});
  current.forEach((item,number)=>{const payload=payloadOf(item);const help=String(payload.helpNow||'');const worry=payload.studentState?.worryDetail;const hurt=payload.peerObservations?.hurt||{};
    if(/바로|즉시/.test(help))add('urgent',item,'지금 도움이 필요하다고 응답했어요','학생이 바로 도움을 요청했습니다.',[quoted(worry||hurt.detail),'도움 요청: 바로 도와주세요',hurt.sourceType?`사건 맥락: ${hurt.sourceType}${hurt.frequency?` · ${hurt.frequency}`:''}${hurt.ongoing?' · 지금도 계속됨':''}`:''],['현재 어려움이 계속되는 상황','도움을 요청할 만큼 불편한 상황','학생이 안전한 대화를 원하는 상황'],'오늘 중 안전한 장소에서 현재 상황과 학생이 원하는 도움을 먼저 확인합니다.');
    else if(/이번 주/.test(help))add('week',item,'이번 주에 이야기하고 싶다고 응답했어요','학생이 교사와의 대화를 요청했습니다.',[quoted(worry||hurt.detail),'도움 요청: 이번 주에 이야기하고 싶어요'],['최근 학교생활 고민','친구 관계에서의 불편함','교사와 확인하고 싶은 개인적인 상황'],'이번 주 안에 개별적으로 편안한 시간과 장소를 정해 이야기를 듣습니다.');
    const before=previous.get(number);if(before){const nowRatings=payload.selfRatings||{};const oldRatings=payloadOf(before).selfRatings||{};const labels={study:'학습',listening:'경청',respect:'관계 존중',manners:'예의',responsibility:'책임감'};const drops=Object.keys(labels).filter(key=>Number(oldRatings[key]?.score)-Number(nowRatings[key]?.score)>=2);if(drops.length)add('week',item,'자기평가가 지난달보다 크게 낮아졌어요',drops.map(key=>`${labels[key]} ${oldRatings[key].score}→${nowRatings[key].score}`).join(' · '),drops.map(key=>`${labels[key]}: ${previousMonth(month)} ${oldRatings[key].score}점 → ${month} ${nowRatings[key].score}점`).concat(quoted(worry)),['최근 경험이나 자신감의 변화','응답 시점의 일시적인 감정','학습·관계 환경의 변화'],'낮아진 항목과 관련된 최근 상황을 학생에게 묻고 수업·쉬는 시간 행동을 함께 살펴봅니다.')}});
  const names=classSettings.students.map(student=>student.name).filter(Boolean);const helpMentions=new Map();current.forEach(item=>{const detail=String(payloadOf(item).peerObservations?.needsHelp?.detail||'');names.forEach(name=>{if(detail.includes(name)){if(!helpMentions.has(name))helpMentions.set(name,[]);helpMentions.get(name).push({item,detail})}})});helpMentions.forEach((mentions,name)=>{const reporters=new Set(mentions.map(({item})=>Number(item.student_number||payloadOf(item).studentNumber)));if(reporters.size>=2){const target=classSettings.students.find(student=>student.name===name);add('week',{student_name:name},'여러 친구가 도움이 필요하다고 언급했어요',`서로 다른 ${reporters.size}명의 응답에 등장했습니다.`,mentions.slice(0,3).map(({item,detail})=>`${item.student_name||payloadOf(item).studentName}: ${quoted(detail)}`),['학습이나 활동에서 도움이 필요한 상황','친구 관계에서 지원이 필요한 상황','친구들이 걱정하거나 함께 돕고 싶은 상황'],'학습·놀이·모둠 상황을 살펴본 뒤 학생에게 필요한 도움이 있는지 부담 없이 확인합니다.')}});
  const relationMap=new Map();current.forEach((item,rater)=>{(payloadOf(item).relationships||[]).forEach(row=>relationMap.set(`${rater}:${Number(row.targetNumber)}`,Number(row.score)))});const incoming=new Map();relationMap.forEach((score,key)=>{const target=Number(key.split(':')[1]);if(!incoming.has(target))incoming.set(target,[]);incoming.get(target).push(score)});incoming.forEach((values,target)=>{if(values.length<4)return;const low=values.filter(value=>value<=2).length/values.length;const high=values.filter(value=>value>=4).length/values.length;const sd=standardDeviation(values);if(low>=.25&&high>=.25&&sd>=1.3){const student=classSettings.students.find(row=>Number(row.number)===target);add('week',{student_name:student?.name||`${target}번 학생`},'친구에 따라 관계 경험이 다르게 나타나요',`1~2점 ${Math.round(low*100)}% · 4~5점 ${Math.round(high*100)}% · 표준편차 ${sd.toFixed(1)}`,[`수신 관계 응답 ${values.length}건: ${values.join(', ')}점`,`평균 ${(values.reduce((a,b)=>a+b,0)/values.length).toFixed(1)}점 · 표준편차 ${sd.toFixed(1)}`],['친구 집단별 상호작용 차이','활동 상황에 따른 관계 경험 차이','응답 시점의 감정 차이'],'모둠과 놀이 집단에 따라 말투·접근·상대 반응이 달라지는지 확인합니다.')}});
  const checkedPairs=new Set();relationMap.forEach((score,key)=>{const [a,b]=key.split(':').map(Number);const pair=[a,b].sort((x,y)=>x-y).join(':');if(checkedPairs.has(pair))return;checkedPairs.add(pair);const reverse=relationMap.get(`${b}:${a}`);if(reverse!==undefined&&Math.abs(score-reverse)>=2){const aName=classSettings.students.find(row=>Number(row.number)===a)?.name||`${a}번`;const bName=classSettings.students.find(row=>Number(row.number)===b)?.name||`${b}번`;add('watch',{student_name:`${aName} ↔ ${bName}`},'서로 느끼는 관계에 차이가 있어요',`${aName}→${bName} ${score}점 · ${bName}→${aName} ${reverse}점`,[`방향별 관계 점수 차이 ${Math.abs(score-reverse)}점`],['관계 기대의 차이','접근·거절 신호에 대한 이해 차이','응답 시점의 일시적인 감정'],'두 학생을 따로 살펴보고 서로의 접근과 반응을 어떻게 느끼는지 자연스럽게 확인합니다.')}});
  const previousRelationMap=new Map();previous.forEach((item,rater)=>{(payloadOf(item).relationships||[]).forEach(row=>previousRelationMap.set(`${rater}:${Number(row.targetNumber)}`,Number(row.score)))});
  const mutualHighCount=(map,number)=>classSettings.students.filter(student=>Number(student.number)!==number).filter(student=>{const other=Number(student.number);return map.get(`${number}:${other}`)>=4&&map.get(`${other}:${number}`)>=4}).length;
  const positiveMentions=new Map();current.forEach(item=>{const peer=payloadOf(item).peerObservations||{};const text=`${peer.kind?.detail||''} ${peer.growth?.detail||''}`;names.forEach(name=>{if(text.includes(name))positiveMentions.set(name,(positiveMentions.get(name)||0)+1)})});
  classSettings.students.forEach(student=>{const number=Number(student.number);const values=incoming.get(number)||[];if(values.length<4)return;const highCount=values.filter(value=>value>=4).length;const highRatio=highCount/values.length;const mutualNow=mutualHighCount(relationMap,number);const mutualBefore=mutualHighCount(previousRelationMap,number);const unreciprocated=classSettings.students.filter(other=>Number(other.number)!==number).filter(other=>relationMap.get(`${number}:${Number(other.number)}`)>=4&&relationMap.get(`${Number(other.number)}:${number}`)<=2).length;const own=payloadOf(current.get(number));const relationWorry=/친구|관계|혼자|놀/.test(String(own.studentState?.worryDetail||''));const helpCount=new Set((helpMentions.get(student.name)||[]).map(({item})=>Number(item.student_number||payloadOf(item).studentNumber))).size;const relationFlags=[];if(mutualNow<=1)relationFlags.push(`상호 4~5점 연결 ${mutualNow}명`);if(highRatio<=.25)relationFlags.push(`받은 4~5점 ${highCount}/${values.length}건`);if(mutualBefore-mutualNow>=2)relationFlags.push(`상호 높은 연결 ${mutualBefore}→${mutualNow}명`);if(unreciprocated>=2)relationFlags.push(`본인은 높게 평가했지만 되돌아온 점수가 낮은 관계 ${unreciprocated}명`);const contextFlags=[];if(relationWorry)contextFlags.push('본인이 친구 관계 고민을 작성함');if(helpCount>=2)contextFlags.push(`서로 다른 친구 ${helpCount}명이 도움 필요로 언급`);if(relationFlags.length&&relationFlags.length+contextFlags.length>=2){const urgentContext=relationWorry||helpCount>=2||mutualBefore-mutualNow>=2;add(urgentContext?'week':'watch',{student_name:student.name,student_number:number},'관계 연결을 실제 상황에서 확인해 주세요',[...relationFlags,...contextFlags].join(' · '),[...relationFlags,...contextFlags,`수신 관계 점수 ${values.length}건 · 평균 ${(values.reduce((sum,value)=>sum+value,0)/values.length).toFixed(1)}점`],['최근 자리·모둠·놀이 상대의 변화','특정 활동에서만 관계가 이어지는 상황','응답하지 않은 친구와 실제로 친밀할 가능성'],'5일 동안 쉬는 시간 3회와 모둠 활동 2회에서 먼저 접근하는 친구, 상대 반응, 혼자 있는 시간과 참여 기회를 사실 중심으로 기록합니다.')}});
  found.forEach(signal=>{const student=classSettings.students.find(row=>row.name===signal.name);if(!student){signal.protectiveFactors=[];return}const number=Number(student.number);const values=incoming.get(number)||[];const mutual=mutualHighCount(relationMap,number);const positive=positiveMentions.get(student.name)||0;signal.protectiveFactors=[mutual>=2?`상호 높은 관계 ${mutual}명`:null,values.filter(value=>value>=4).length>=2?`받은 4~5점 ${values.filter(value=>value>=4).length}건`:null,positive?`친절·성장 긍정 언급 ${positive}건`:null].filter(Boolean)});
  return found.sort((a,b)=>({urgent:0,week:1,watch:2}[a.type]-{urgent:0,week:1,watch:2}[b.type]));
}
function groupedSignals(filter='all'){const groups=new Map();signals.forEach(signal=>{if(!groups.has(signal.name))groups.set(signal.name,[]);groups.get(signal.name).push(signal)});return[...groups.entries()].map(([name,items])=>{const type=items.some(item=>item.type==='urgent')?'urgent':items.some(item=>item.type==='week')?'week':'watch';const student=classSettings.students.find(row=>row.name===name);const hasPrevious=student&&latestByStudent(allResponses,previousMonth(selectedAnalysisMonth)).has(Number(student.number));const changed=items.some(item=>item.evidence.some(evidence=>String(evidence).includes('→')));const trend=!hasPrevious?'전월 비교 자료 없음':changed?'전월 대비 변화 확인':'이번 달 확인 신호';const protectiveFactors=[...new Set(items.flatMap(item=>item.protectiveFactors||[]))];return{name,items,type,tag:signalTag(type),ids:items.map(item=>item.id),trend,protectiveFactors}}).filter(group=>filter==='all'||group.type===filter).sort((a,b)=>({urgent:0,week:1,watch:2}[a.type]-{urgent:0,week:1,watch:2}[b.type]))}
function renderAnalysisStatus(){const current=latestByStudent(allResponses,selectedAnalysisMonth);const total=classSettings.students.length;const submitted=current.size;const rate=total?Math.round(submitted/total*100):0;const monthlyRows=allResponses.filter(item=>monthOf(item)===selectedAnalysisMonth);const duplicateCount=Math.max(0,monthlyRows.length-submitted);const relationshipCount=[...current.values()].filter(item=>(payloadOf(item).relationships||[]).length).length;const relationshipRate=total?Math.round(relationshipCount/total*100):0;const relationshipReady=rate>=80&&relationshipCount>=Math.ceil(total*.8);const concernCounts={친구:0,공부:0,성적:0,등하교:0,가정:0};current.forEach(item=>{const text=String(payloadOf(item).studentState?.worryDetail||'');Object.keys(concernCounts).forEach(key=>{if(text.includes(key))concernCounts[key]++})});const concerns=Object.entries(concernCounts).filter(([,count])=>count).sort((a,b)=>b[1]-a[1]).map(([key,count])=>`${key} ${count}건`).join(' · ')||'분류된 공통 고민 없음';const el=$('#analysisDataStatus');el.className=`notice ${relationshipReady?'safe':'warning'}`;el.innerHTML=`<span>${relationshipReady?'✓':'!'}</span><div><strong>${monthLabel(selectedAnalysisMonth)} 데이터 상태 · 제출 ${submitted}/${total}명 (${rate}%) · 관계 문항 ${relationshipCount}/${total}명 (${relationshipRate}%)</strong><p>학생별 최신 제출을 분석합니다${duplicateCount?` · 추가 제출 ${duplicateCount}건은 최신 응답으로 대체됨`:''}. 관계 구조 분석: <b>${relationshipReady?'참고 가능':'데이터 부족'}</b>${relationshipReady?'':' (제출·관계 문항 응답률 80% 이상 필요)'} · 공통 고민: ${escapeHTML(concerns)}</p></div>`}
function loadClassSettings(){try{const saved=JSON.parse(localStorage.getItem('ieum-class-settings'));if(saved?.students?.length)return{...defaultSettings,...saved,students:saved.students.map((student,index)=>({...student,accessCode:student.accessCode||String(731204+index*7919).slice(-6)}))}}catch(error){}return JSON.parse(JSON.stringify(defaultSettings))}
function persistClassSettings(){localStorage.setItem('ieum-class-settings',JSON.stringify(classSettings))}
function syncSignalNames(){}
function renderClassIdentity(){const {teacherName,schoolYear,grade,classNumber}=classSettings;$('#profileAvatar').textContent=teacherName.trim().charAt(0)||'교';$('#profileTeacher').textContent=`${teacherName} 선생님`;$('#profileClass').textContent=`${grade}학년 ${classNumber}반 담임`;$('#classEyebrow').textContent=`${schoolYear}학년도 · ${grade}학년 ${classNumber}반`}
function renderSettings(){const {teacherName,schoolYear,grade,classNumber,classId,teacherSecret,students}=classSettings;$('#teacherName').value=teacherName;$('#schoolYear').value=schoolYear;$('#grade').value=grade;$('#classNumber').value=classNumber;$('#classId').value=classId||'';$('#teacherSecret').value=teacherSecret||'';$('#rosterCount').textContent=`${students.length}명`;$('#rosterBody').innerHTML=students.map((student,index)=>`<tr><td><input type="number" min="1" max="99" value="${student.number}" data-student-number="${index}" aria-label="${index+1}번째 학생 번호"></td><td><input maxlength="20" value="${escapeHTML(student.name)}" data-student-name="${index}" aria-label="${index+1}번째 학생 이름"></td><td><button class="remove-student" type="button" data-remove-student="${index}" aria-label="${escapeHTML(student.name)} 삭제">삭제</button></td></tr>`).join('')}
function collectSettingsForm(){const students=$$('#rosterBody tr').map((row,index)=>({number:Number(row.querySelector('[data-student-number]').value),name:row.querySelector('[data-student-name]').value.trim(),accessCode:classSettings.students[index]?.accessCode||''})).filter(student=>student.name).sort((a,b)=>a.number-b.number);return{teacherName:$('#teacherName').value.trim(),schoolYear:Number($('#schoolYear').value),grade:Number($('#grade').value),classNumber:Number($('#classNumber').value),classId:$('#classId').value.trim(),teacherSecret:$('#teacherSecret').value.trim(),students}}
function applySettings(){const next=collectSettingsForm();if(!next.teacherName||!next.students.length){showToast('교사 이름과 학생을 한 명 이상 입력해 주세요.');return}classSettings=next;persistClassSettings();syncSignalNames();renderClassIdentity();renderSettings();renderStudents();renderParticipationLink();renderHomeSignals();renderAnalysis($('.filter-tabs .active')?.dataset.filter||'all');showToast('학급 설정을 저장했습니다.')}
function renderParticipationLink(){const url=new URL('student.html',location.href);url.searchParams.set('class',classSettings.classId||`${classSettings.schoolYear}-${classSettings.grade}-${classSettings.classNumber}`);const code=document.querySelector('.copy-row code');if(code)code.textContent=url.href;$('#copyLink').dataset.link=url.href}
function renderResponses(responses){const month=selectedAnalysisMonth||new Date().toISOString().slice(0,7);const monthly=responses.filter(item=>monthOf(item)===month);const submittedNumbers=new Set(monthly.map(item=>Number(item.student_number||payloadOf(item).studentNumber)));const total=classSettings.students.length;const submitted=submittedNumbers.size;const rate=total?Math.round(submitted/total*100):0;$('#studentGrid').innerHTML=classSettings.students.map(student=>`<span class="student-chip ${submittedNumbers.has(Number(student.number))?'':'missing'}">${escapeHTML(student.name)}</span>`).join('');$('#surveyParticipation').textContent=`${submitted} / ${total}명 · ${monthLabel(month)}`;$('#surveyParticipationBar').style.width=`${rate}%`;$('#homeParticipation').innerHTML=`${submitted} <small>/ ${total}명</small>`;$('#homeParticipationBar').style.width=`${rate}%`;$('#homeParticipationText').textContent=`${monthLabel(month)} ${rate}% 참여 · 미제출 ${Math.max(0,total-submitted)}명`;$('#responseList').innerHTML=monthly.length?`<h4>${monthLabel(month)} 제출 원문</h4>`+monthly.map(item=>{const payload=payloadOf(item);const name=item.student_name||payload.studentName||classSettings.students.find(student=>student.number===payload.studentNumber)?.name||'학생';const help=payload.helpNow||'괜찮음';const worry=payload.studentState?.worryDetail||'작성 내용 없음';return`<details><summary><strong>${escapeHTML(name)}</strong><span class="tag ${/바로|즉시/.test(help)?'urgent':/이번 주/.test(help)?'week':'watch'}">${escapeHTML(help)}</span></summary><p>${escapeHTML(worry)}</p></details>`}).join(''):'<p class="muted">선택한 월에 저장된 응답이 없습니다.</p>';renderMonthlySurveyAccordion(responses)}
function renderMonthlySurveyAccordion(responses){const container=$('#monthlySurveyAccordion');if(!container)return;const months=[...new Set(responses.map(monthOf).filter(month=>/^\d{4}-\d{2}$/.test(month)))].sort().reverse();const total=classSettings.students.length;if(!months.length){container.innerHTML='<h4>월별 설문 현황</h4><p class="muted">저장된 월별 설문이 없습니다.</p>';return}container.innerHTML='<h4>월별 설문 현황</h4>'+months.map((month,index)=>{const rows=responses.filter(item=>monthOf(item)===month);const latest=latestByStudent(rows,month);const submitted=[...latest.keys()];const submittedSet=new Set(submitted);const rate=total?Math.round(submitted.length/total*100):0;const missing=classSettings.students.filter(student=>!submittedSet.has(Number(student.number)));const duplicateCount=Math.max(0,rows.length-submitted.length);const submittedNames=classSettings.students.filter(student=>submittedSet.has(Number(student.number))).map(student=>student.name);return`<details ${month===selectedAnalysisMonth||(!selectedAnalysisMonth&&index===0)?'open':''}><summary><strong>${monthLabel(month)}</strong><span class="tag ${rate>=80?'open':rate?'week':'watch'}">${submitted.length}/${total}명 · ${rate}%</span></summary><div class="evidence-box"><p><strong>제출 학생 ${submitted.length}명</strong></p><p>${submittedNames.length?submittedNames.map(escapeHTML).join(', '):'없음'}</p><p><strong>미제출 학생 ${missing.length}명</strong></p><p>${missing.length?missing.map(student=>escapeHTML(student.name)).join(', '):'없음'}</p><p class="muted">저장된 응답 ${rows.length}건${duplicateCount?` · 추가 제출 ${duplicateCount}건`:''}</p><button type="button" class="text-button" data-select-survey-month="${month}">이 월의 원문·분석 보기 →</button></div></details>`}).join('')}
function normalizeParticipationLabel(){const label=$('#surveyParticipation');if(label)label.textContent=label.textContent.split(' · ')[0];const responseList=$('#responseList');if(responseList)responseList.innerHTML=''}
function applyAnalysisMonth(){signals=analyzeResponses(allResponses,selectedAnalysisMonth);renderResponses(allResponses);normalizeParticipationLabel();renderAnalysisStatus();renderHomeSignals();renderAnalysis($('.filter-tabs .active')?.dataset.filter||'all')}
async function refreshResponses(showNotice=true){if(!classSettings.teacherSecret){if(showNotice)showToast('학급 설정에서 교사용 DB 접근 코드를 입력해 주세요.');return}try{allResponses=await supabaseRpc('teacher_get_responses',{p_class_id:classSettings.classId,p_secret:classSettings.teacherSecret});updateMonthSelector();applyAnalysisMonth();if(showNotice)showToast('DB 응답을 불러와 분석했습니다.')}catch(error){showToast(`응답을 불러오지 못했습니다: ${error.message}`)}}
async function syncRoster(){applySettings();if(!classSettings.teacherSecret){showToast('교사용 DB 접근 코드를 먼저 입력해 주세요.');return}try{const count=await supabaseRpc('teacher_sync_roster',{p_class_id:classSettings.classId,p_secret:classSettings.teacherSecret,p_students:classSettings.students.map(({number,name})=>({number,name}))});showToast(`${count}명의 명단을 DB에 동기화했습니다.`)}catch(error){showToast(`명단 동기화 실패: ${error.message}`)}}
function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderHomeSignals(){const groups=groupedSignals();const urgent=groups.filter(group=>group.type==='urgent').length;const weekStudents=groups.filter(group=>group.type==='week').length;const latest=latestByStudent(allResponses,selectedAnalysisMonth);const positive=[...latest.values()].filter(item=>{const peer=payloadOf(item).peerObservations||{};return peer.kind?.detail||peer.growth?.detail}).length;$('#homeUrgent').innerHTML=`${urgent} <small>명</small>`;$('#homeWeek').innerHTML=`${weekStudents} <small>명</small>`;$('#homePositive').innerHTML=`${positive} <small>건</small>`;$('#signalList').innerHTML=groups.length?groups.slice(0,3).map(group=>`<article class="signal-item ${group.type}"><i class="signal-bar"></i><div><span class="tag ${group.type}">${group.tag}</span><h3>${escapeHTML(group.name)} · ${group.items.length}개 확인 신호</h3><p>${escapeHTML(group.items.map(item=>item.title).join(' · '))}</p></div><button class="evidence-button" data-evidence-group="${group.ids.join(',')}">통합 근거 보기</button></article>`).join(''):'<p class="muted">선택한 월에 규칙 기반 지원 신호가 없습니다.</p>'}
function renderAnalysis(filter='all'){const allGroups=groupedSignals();const counts={all:allGroups.length,urgent:allGroups.filter(group=>group.type==='urgent').length,week:allGroups.filter(group=>group.type==='week').length,watch:allGroups.filter(group=>group.type==='watch').length};$$('.filter-tabs button').forEach(button=>{const labels={all:'전체',urgent:'즉시 확인',week:'이번 주',watch:'지속 관찰'};button.textContent=`${labels[button.dataset.filter]} ${counts[button.dataset.filter]}`});const visible=groupedSignals(filter);$('#analysisCards').innerHTML=visible.length?visible.map(group=>{const evidenceCount=group.items.reduce((sum,item)=>sum+item.evidence.length,0);return`<article class="analysis-card" data-type="${group.type}"><header><div><div class="analysis-card-tags"><span class="tag ${group.type}">${group.tag}</span><span class="change-badge">${escapeHTML(group.trend)}</span></div><h3>${escapeHTML(group.name)} · 통합 확인 카드</h3><div class="signal-summary">${group.items.map(item=>`<p><strong>▣ ${escapeHTML(item.title)}</strong><br>${escapeHTML(item.summary)}</p>`).join('')}</div>${group.protectiveFactors.length?`<div class="protective-factors"><strong>긍정적 보호요인</strong><p>${group.protectiveFactors.map(item=>`✓ ${escapeHTML(item)}`).join(' · ')}</p></div>`:''}</div></header><footer><span class="evidence-count">신호 ${group.items.length}개 · 근거 ${evidenceCount}개</span><button class="evidence-button" data-evidence-group="${group.ids.join(',')}">통합 근거와 관찰 제안</button></footer></article>`}).join(''):'<div class="panel"><p class="muted">선택한 조건에 해당하는 실제 응답 신호가 없습니다.</p></div>'}
function renderStudents(){renderResponses([])}
function getObservations(){return JSON.parse(localStorage.getItem('ieum-observations')||'null')||[{id:1,status:'todo',student:'김하린',title:'쉬는 시간 관계 관찰',detail:'접근 대상과 상대 반응을 각각 2회 이상 기록',date:'7월 22일까지'},{id:2,status:'doing',student:'박도윤',title:'모둠별 상호작용 확인',detail:'말투와 장난의 강도가 상황별로 다른지 확인',date:'3 / 5회 기록'},{id:3,status:'done',student:'윤서아',title:'긍정 행동 확인',detail:'친구에게 설명해 주는 행동이 반복됨',date:'7월 18일 완료'}]}
function saveObservations(items){localStorage.setItem('ieum-observations',JSON.stringify(items));renderObservations()}
function renderObservations(){const items=getObservations();const cols=[['todo','관찰 예정'],['doing','관찰 중'],['done','확인 완료']];$('#observationBoard').innerHTML=cols.map(([key,label])=>{const list=items.filter(i=>i.status===key);return `<section class="observation-column"><div class="column-head"><h3>${label}</h3><span>${list.length}</span></div>${list.map(i=>`<article class="observation-card"><span class="tag ${key==='done'?'open':key==='doing'?'week':'watch'}">${i.student}</span><h4>${i.title}</h4><p>${i.detail}</p><footer><span>${i.date}</span>${key!=='done'?`<button class="text-button" data-advance="${i.id}">다음 단계 →</button>`:'<span>✓ 확인됨</span>'}</footer></article>`).join('')||'<p class="muted">기록이 없습니다.</p>'}</section>`}).join('')}
function openEvidence(id){const s=signals.find(x=>x.id===Number(id));if(!s)return;$('#dialogTitle').textContent=`${s.name} · ${s.title}`;$('#dialogContent').innerHTML=`<h3>연결된 근거</h3>${s.evidence.map(e=>`<div class="evidence-box">${escapeHTML(e)}</div>`).join('')}<h3>가능한 해석</h3><div class="hypotheses">${s.hypotheses.map(h=>`<span>${escapeHTML(h)}</span>`).join('')}</div><h3>추천 관찰</h3><p>${escapeHTML(s.observation)}</p><div class="notice warning"><span>!</span><p>가능성에 대한 가설입니다. 원문 검토와 실제 관찰·대화로 확인해 주세요.</p></div>`;$('#saveObservation').dataset.signal=id;delete $('#saveObservation').dataset.signalGroup;$('#evidenceDialog').showModal()}
function openEvidenceGroup(ids){const items=String(ids).split(',').map(Number).map(id=>signals.find(signal=>signal.id===id)).filter(Boolean);if(!items.length)return;const name=items[0].name;$('#dialogTitle').textContent=`${name} · 통합 근거`;$('#dialogContent').innerHTML=items.map(item=>`<section><span class="tag ${item.type}">${item.tag}</span><h3>▣ 계산·분류 결과</h3><p><strong>${escapeHTML(item.title)}</strong><br>${escapeHTML(item.summary)}</p><h3>“ ” 연결된 학생 응답·계산 근거</h3>${item.evidence.map(e=>`<div class="evidence-box">${escapeHTML(e)}</div>`).join('')}<h3>? 가능한 해석</h3><div class="hypotheses">${item.hypotheses.map(h=>`<span>${escapeHTML(h)}</span>`).join('')}</div><h3>✓ 교사 확인 제안</h3><p>${escapeHTML(item.observation)}</p></section>`).join('<hr>')+`<div class="notice warning"><span>!</span><p>계산 결과와 가능성에 대한 가설입니다. 원문 검토와 실제 관찰·대화로 확인해 주세요.</p></div>`;$('#saveObservation').dataset.signal=items[0].id;$('#saveObservation').dataset.signalGroup=items.map(item=>item.id).join(',');$('#evidenceDialog').showModal()}
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{const view=btn.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$('#pageTitle').textContent=pageTitles[view];if(view==='settings')renderSettings();$('#sidebar').classList.remove('open');window.scrollTo(0,0)}));
document.addEventListener('click',e=>{const evidenceGroup=e.target.closest('[data-evidence-group]');if(evidenceGroup)openEvidenceGroup(evidenceGroup.dataset.evidenceGroup);else{const evidence=e.target.closest('[data-evidence]');if(evidence)openEvidence(evidence.dataset.evidence)}const closer=e.target.closest('[data-close]');if(closer)closer.closest('dialog').close();const go=e.target.closest('[data-go]');if(go)$(`.nav-item[data-view="${go.dataset.go}"]`).click();const advance=e.target.closest('[data-advance]');if(advance){const items=getObservations();const item=items.find(i=>i.id===Number(advance.dataset.advance));item.status=item.status==='todo'?'doing':'done';saveObservations(items);showToast('관찰 상태를 변경했습니다.')}const remove=e.target.closest('[data-remove-student]');if(remove){classSettings=collectSettingsForm();classSettings.students.splice(Number(remove.dataset.removeStudent),1);renderSettings();showToast('명단에서 삭제했습니다. 저장 버튼을 눌러 확정하세요.')}});
$('.filter-tabs').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;$$('.filter-tabs button').forEach(b=>b.classList.toggle('active',b===e.target));renderAnalysis(e.target.dataset.filter)});
document.addEventListener('click',event=>{const monthButton=event.target.closest('[data-select-survey-month]');if(!monthButton)return;selectedAnalysisMonth=monthButton.dataset.selectSurveyMonth;$('#analysisMonth').value=selectedAnalysisMonth;$('#surveyMonth').value=selectedAnalysisMonth;applyAnalysisMonth();showToast(`${monthLabel(selectedAnalysisMonth)} 현황을 선택했습니다.`)});
$('#saveObservation').addEventListener('click',e=>{const groupIds=String(e.target.dataset.signalGroup||e.target.dataset.signal).split(',').map(Number);const selected=groupIds.map(id=>signals.find(signal=>signal.id===id)).filter(Boolean);const s=selected[0];if(!s)return;const items=getObservations();items.unshift({id:Date.now(),status:'todo',student:s.name,title:selected.length>1?`${selected.length}개 신호 통합 확인`:s.title,detail:selected.map(item=>item.observation).join(' / '),date:'이번 주'});saveObservations(items);delete e.target.dataset.signalGroup;$('#evidenceDialog').close();showToast('통합 관찰 과제로 저장했습니다.')});
$('#addObservation').addEventListener('click',()=>{const items=getObservations();items.unshift({id:Date.now(),status:'todo',student:'학생 선택',title:'새 관찰 기록',detail:'구체적인 시간·상황·행동을 기록해 주세요.',date:'날짜 미정'});saveObservations(items);showToast('새 관찰 기록을 추가했습니다.')});
$('#copyLink').addEventListener('click',event=>{navigator.clipboard?.writeText(event.currentTarget.dataset.link);showToast('참여 링크를 복사했습니다.')});
$('#refreshResponses').addEventListener('click',refreshResponses);
$('#analysisMonth').addEventListener('change',event=>{selectedAnalysisMonth=event.target.value;applyAnalysisMonth()});
$('#surveyMonth').addEventListener('change',event=>{selectedAnalysisMonth=event.target.value;$('#analysisMonth').value=selectedAnalysisMonth;applyAnalysisMonth()});
$('#syncRoster').addEventListener('click',syncRoster);
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#saveSettings').addEventListener('click',applySettings);
$('#classSettingsForm').addEventListener('submit',event=>{event.preventDefault();applySettings()});
$('#addStudent').addEventListener('click',()=>{classSettings=collectSettingsForm();const number=classSettings.students.length?Math.max(...classSettings.students.map(student=>student.number))+1:1;classSettings.students.push({number,name:'',accessCode:String(Math.floor(100000+Math.random()*900000))});renderSettings();const inputs=$$('[data-student-name]');inputs.at(-1)?.focus()});
$('#pasteRoster').addEventListener('click',()=>{$('#rosterPaste').value='';$('#pasteDialog').showModal()});
$('#applyRosterPaste').addEventListener('click',()=>{const parsed=$('#rosterPaste').value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const parts=line.split(/[,\t]/).map(part=>part.trim());const hasNumber=parts.length>1&&!Number.isNaN(Number(parts[0]));return{number:hasNumber?Number(parts[0]):index+1,name:hasNumber?parts.slice(1).join(' '):parts.join(' ')}}).filter(student=>student.name);if(!parsed.length){showToast('붙여넣을 학생 이름을 입력해 주세요.');return}classSettings={...collectSettingsForm(),students:parsed};renderSettings();$('#pasteDialog').close();showToast(`${parsed.length}명의 명단을 불러왔습니다. 저장 버튼을 눌러 확정하세요.`)});
$('#toggleNames').addEventListener('click',e=>{const show=$('#network').classList.toggle('show-names');e.target.textContent=show?'이름 숨기기':'이름 표시';$$('.nodes g').forEach(g=>{const original=g.querySelector('text');original.textContent=show?g.querySelector('title').textContent:original.textContent.charAt(0)})});
const steps=[`<div class="survey-question"><p class="eyebrow">나의 학교생활</p><h2>이번 달에 친구를 존중하며 이야기했나요?</h2><p>가장 가까운 답을 골라 주세요. 점수는 평가나 순위에 사용되지 않아요.</p><div class="rating-options">${[1,2,3,4,5].map((n,i)=>`<label><input type="radio" name="rating" value="${n}" ${n===4?'checked':''}><strong>${n}점</strong> · ${['거의 못했어요','조금 어려웠어요','보통이에요','잘했어요','매우 잘했어요'][i]}</label>`).join('')}</div></div>`,`<div class="survey-question"><p class="eyebrow">내 마음 표현하기</p><h2>요즘 학교생활에서 마음에 걸리는 일이 있나요?</h2><p>직접 겪은 일과 들은 일을 구분해서, 기억나는 만큼만 적어도 괜찮아요.</p><textarea placeholder="언제, 어디서, 어떤 일이 있었는지 적어 주세요."></textarea></div>`,`<div class="survey-question"><p class="eyebrow">도움 요청</p><h2>선생님의 도움이 지금 필요한가요?</h2><p>급한 도움이 필요하면 설문을 기다리지 말고 바로 선생님께 알려 주세요.</p><div class="help-choice"><label><input type="radio" name="help" checked> 지금은 괜찮아요.</label><label><input type="radio" name="help"> 이번 주에 이야기하고 싶어요.</label><label><input type="radio" name="help"> 바로 도와주세요.</label></div></div>`];let step=0;
function renderStep(){ $('#surveyStep').innerHTML=steps[step];$('#stepLabel').textContent=`${step+1} / ${steps.length}`;$('#surveyProgress').style.width=`${(step+1)/steps.length*100}%`;$('#prevStep').style.visibility=step?'visible':'hidden';$('#nextStep').textContent=step===steps.length-1?'제출하기':'다음'}
$('#openStudentSurvey').addEventListener('click',event=>{event.currentTarget.href=$('#copyLink').dataset.link});
$('#prevStep').addEventListener('click',()=>{if(step){step--;renderStep()}});$('#nextStep').addEventListener('click',()=>{if(step<steps.length-1){step++;renderStep()}else{$('#studentDialog').close();showToast('미리보기 설문이 제출되었습니다.')}});
selectedAnalysisMonth=new Date().toISOString().slice(0,7);syncSignalNames();renderClassIdentity();updateMonthSelector();renderAnalysisStatus();renderHomeSignals();renderAnalysis();renderStudents();renderObservations();renderSettings();renderParticipationLink();renderResponses([]);normalizeParticipationLabel();if(classSettings.teacherSecret)refreshResponses(false);
