const signals = [
  {id:1,type:'urgent',tag:'즉시 확인',name:'한지우',title:'지금 도움이 필요하다고 응답했어요',summary:'쉬는 시간에 반복되는 불편함과 즉시 도움 요청',evidence:['“쉬는 시간마다 제 물건을 가져가고 돌려주지 않아요.”','도움 요청: 바로 선생님의 도움이 필요해요','사건 맥락: 직접 경험 · 이번 달 3회 이상 · 계속됨'],hypotheses:['친구 사이의 경계 설정 어려움','반복되는 장난','관계 갈등'],observation:'오늘 중 개별적으로 안전한 장소에서 현재 상황과 원하는 도움을 확인합니다.'},
  {id:2,type:'week',tag:'이번 주 확인',name:'김하린',title:'관계 자기평가가 지난달보다 낮아졌어요',summary:'관계 존중 4→2 · 도움 필요 언급 2건',evidence:['“요즘 같이 놀던 친구들이 다른 놀이를 해서 혼자 있을 때가 있어요.”','관계 자기평가: 6월 4점 → 7월 2점','서로 다른 학생 2명이 도움 필요 친구로 선택'],hypotheses:['놀이 집단 변화','최근 친구 갈등','일시적인 감정'],observation:'5일간 쉬는 시간의 접근 대상과 상대 반응을 각각 2회 이상 기록합니다.'},
  {id:3,type:'week',tag:'이번 주 확인',name:'박도윤',title:'친구에 따라 관계 경험이 다르게 나타나요',summary:'1~2점 38% · 4~5점 42% · 분산 높음',evidence:['수신 관계 점수 평균 3.1 · 표준편차 1.6','긍정 언급 4건과 불편 언급 3건이 함께 나타남'],hypotheses:['집단별 상호작용 차이','장난 강도의 차이','활동 맥락의 차이'],observation:'모둠과 놀이 집단에 따라 말투와 장난의 강도가 달라지는지 살펴봅니다.'},
  {id:4,type:'week',tag:'이번 주 확인',name:'최유나',title:'서로 느끼는 친밀감에 차이가 있어요',summary:'최유나→정민재 5점 · 정민재→최유나 2점',evidence:['방향별 관계 점수 차이 3점','자유서술에 직접적인 갈등 언급은 없음'],hypotheses:['관계 기대의 차이','접근 신호의 오해','응답 시점의 감정'],observation:'접근과 거절 신호를 서로 어떻게 이해하는지 자연스럽게 확인합니다.'},
  {id:5,type:'watch',tag:'지속 관찰',name:'이서준',title:'강한 상호 연결이 지난달보다 줄었어요',summary:'상호 높은 관계 3쌍→1쌍',evidence:['상호 4~5점 연결이 전월 대비 2쌍 감소','본인 자기평가에는 큰 변화 없음'],hypotheses:['자리·모둠 변화','관심 활동의 변화','응답자 구성 차이'],observation:'쉬는 시간과 모둠에서 실제 참여 방식과 먼저 접근하는 대상을 관찰합니다.'}
];
const defaultStudentNames=['김하린','박도윤','이서준','최유나','정민재','윤서아','한지우','강민준','송지민','임다온','오시우','신예린','조하준','권나윤','안지호','문서윤','장도현','배유진','백시온','류아린','차민서','남도하','유준서','서하은','진우성','표가은','노현우','마지안'];
const defaultSettings={teacherName:'홍현진',schoolYear:2026,grade:5,classNumber:2,classId:'2026-5-2',teacherSecret:'',students:defaultStudentNames.map((name,index)=>({number:index+1,name,accessCode:String(731204+index*7919).slice(-6)}))};
let classSettings=loadClassSettings();
const pageTitles={home:'안녕하세요, 선생님',survey:'설문 관리',analysis:'분석 대시보드',relations:'관계 분석',observations:'관찰 기록',settings:'학급 설정'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function loadClassSettings(){try{const saved=JSON.parse(localStorage.getItem('ieum-class-settings'));if(saved?.students?.length)return{...defaultSettings,...saved,students:saved.students.map((student,index)=>({...student,accessCode:student.accessCode||String(731204+index*7919).slice(-6)}))}}catch(error){}return JSON.parse(JSON.stringify(defaultSettings))}
function persistClassSettings(){localStorage.setItem('ieum-class-settings',JSON.stringify(classSettings))}
function syncSignalNames(){const indexes=[6,0,1,3,2];signals.forEach((signal,index)=>{signal.name=classSettings.students[indexes[index]]?.name||`학생 ${index+1}`})}
function renderClassIdentity(){const {teacherName,schoolYear,grade,classNumber}=classSettings;$('#profileAvatar').textContent=teacherName.trim().charAt(0)||'교';$('#profileTeacher').textContent=`${teacherName} 선생님`;$('#profileClass').textContent=`${grade}학년 ${classNumber}반 담임`;$('#classEyebrow').textContent=`${schoolYear}학년도 · ${grade}학년 ${classNumber}반`}
function renderSettings(){const {teacherName,schoolYear,grade,classNumber,classId,teacherSecret,students}=classSettings;$('#teacherName').value=teacherName;$('#schoolYear').value=schoolYear;$('#grade').value=grade;$('#classNumber').value=classNumber;$('#classId').value=classId||'';$('#teacherSecret').value=teacherSecret||'';$('#rosterCount').textContent=`${students.length}명`;$('#rosterBody').innerHTML=students.map((student,index)=>`<tr><td><input type="number" min="1" max="99" value="${student.number}" data-student-number="${index}" aria-label="${index+1}번째 학생 번호"></td><td><input maxlength="20" value="${escapeHTML(student.name)}" data-student-name="${index}" aria-label="${index+1}번째 학생 이름"></td><td><button class="remove-student" type="button" data-remove-student="${index}" aria-label="${escapeHTML(student.name)} 삭제">삭제</button></td></tr>`).join('')}
function collectSettingsForm(){const students=$$('#rosterBody tr').map((row,index)=>({number:Number(row.querySelector('[data-student-number]').value),name:row.querySelector('[data-student-name]').value.trim(),accessCode:classSettings.students[index]?.accessCode||''})).filter(student=>student.name).sort((a,b)=>a.number-b.number);return{teacherName:$('#teacherName').value.trim(),schoolYear:Number($('#schoolYear').value),grade:Number($('#grade').value),classNumber:Number($('#classNumber').value),classId:$('#classId').value.trim(),teacherSecret:$('#teacherSecret').value.trim(),students}}
function applySettings(){const next=collectSettingsForm();if(!next.teacherName||!next.students.length){showToast('교사 이름과 학생을 한 명 이상 입력해 주세요.');return}classSettings=next;persistClassSettings();syncSignalNames();renderClassIdentity();renderSettings();renderStudents();renderParticipationLink();renderHomeSignals();renderAnalysis($('.filter-tabs .active')?.dataset.filter||'all');showToast('학급 설정을 저장했습니다.')}
function renderParticipationLink(){const url=new URL('student.html',location.href);url.searchParams.set('class',classSettings.classId||`${classSettings.schoolYear}-${classSettings.grade}-${classSettings.classNumber}`);const code=document.querySelector('.copy-row code');if(code)code.textContent=url.href;$('#copyLink').dataset.link=url.href}
function renderResponses(responses){const submittedNumbers=new Set(responses.map(item=>Number(item.student_number||item.studentNumber)));const total=classSettings.students.length;const submitted=submittedNumbers.size;const rate=total?Math.round(submitted/total*100):0;$('#studentGrid').innerHTML=classSettings.students.map(student=>`<span class="student-chip ${submittedNumbers.has(Number(student.number))?'':'missing'}">${escapeHTML(student.name)}</span>`).join('');$('#surveyParticipation').textContent=`${submitted} / ${total}명`;$('#surveyParticipationBar').style.width=`${rate}%`;$('#homeParticipation').innerHTML=`${submitted} <small>/ ${total}명</small>`;$('#homeParticipationBar').style.width=`${rate}%`;$('#homeParticipationText').textContent=`${rate}% 참여 · 미제출 ${Math.max(0,total-submitted)}명`;$('#responseList').innerHTML=responses.length?`<h4>최근 제출 원문</h4>`+responses.map(item=>{let payload=item.payload_json||item;try{if(typeof payload==='string')payload=JSON.parse(payload)}catch(error){}const name=item.student_name||item.studentName||classSettings.students.find(student=>student.number===payload.studentNumber)?.name||'학생';const help=payload.helpNow||item.help_now||'괜찮음';const worry=payload.studentState?.worryDetail||'작성 내용 없음';return`<details><summary><strong>${escapeHTML(name)}</strong><span class="tag ${help==='즉시'?'urgent':help==='이번 주'?'week':'watch'}">${escapeHTML(help)}</span></summary><p>${escapeHTML(worry)}</p></details>`}).join(''):'<p class="muted">아직 저장된 응답이 없습니다.</p>'}
async function refreshResponses(){if(!classSettings.teacherSecret){showToast('학급 설정에서 교사용 DB 접근 코드를 입력해 주세요.');return}try{const responses=await supabaseRpc('teacher_get_responses',{p_class_id:classSettings.classId,p_secret:classSettings.teacherSecret});renderResponses(responses);showToast('DB의 제출 현황을 새로고침했습니다.')}catch(error){showToast(`응답을 불러오지 못했습니다: ${error.message}`)}}
async function syncRoster(){applySettings();if(!classSettings.teacherSecret){showToast('교사용 DB 접근 코드를 먼저 입력해 주세요.');return}try{const count=await supabaseRpc('teacher_sync_roster',{p_class_id:classSettings.classId,p_secret:classSettings.teacherSecret,p_students:classSettings.students.map(({number,name})=>({number,name}))});showToast(`${count}명의 명단을 DB에 동기화했습니다.`)}catch(error){showToast(`명단 동기화 실패: ${error.message}`)}}
function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderHomeSignals(){ $('#signalList').innerHTML=signals.slice(0,3).map(signal=>`<article class="signal-item ${signal.type}"><i class="signal-bar"></i><div><span class="tag ${signal.type}">${signal.tag}</span><h3>${signal.name} · ${signal.title}</h3><p>${signal.summary}</p></div><button class="evidence-button" data-evidence="${signal.id}">근거 보기</button></article>`).join('') }
function renderAnalysis(filter='all'){const visible=filter==='all'?signals:signals.filter(s=>s.type===filter);$('#analysisCards').innerHTML=visible.map(s=>`<article class="analysis-card" data-type="${s.type}"><header><div><span class="tag ${s.type}">${s.tag}</span><h3>${s.name} · ${s.title}</h3><p>${s.summary}</p></div></header><footer><span class="evidence-count">근거 ${s.evidence.length}개 연결됨</span><button class="evidence-button" data-evidence="${s.id}">근거와 관찰 제안 보기</button></footer></article>`).join('')}
function renderStudents(){renderResponses([])}
function getObservations(){return JSON.parse(localStorage.getItem('ieum-observations')||'null')||[{id:1,status:'todo',student:'김하린',title:'쉬는 시간 관계 관찰',detail:'접근 대상과 상대 반응을 각각 2회 이상 기록',date:'7월 22일까지'},{id:2,status:'doing',student:'박도윤',title:'모둠별 상호작용 확인',detail:'말투와 장난의 강도가 상황별로 다른지 확인',date:'3 / 5회 기록'},{id:3,status:'done',student:'윤서아',title:'긍정 행동 확인',detail:'친구에게 설명해 주는 행동이 반복됨',date:'7월 18일 완료'}]}
function saveObservations(items){localStorage.setItem('ieum-observations',JSON.stringify(items));renderObservations()}
function renderObservations(){const items=getObservations();const cols=[['todo','관찰 예정'],['doing','관찰 중'],['done','확인 완료']];$('#observationBoard').innerHTML=cols.map(([key,label])=>{const list=items.filter(i=>i.status===key);return `<section class="observation-column"><div class="column-head"><h3>${label}</h3><span>${list.length}</span></div>${list.map(i=>`<article class="observation-card"><span class="tag ${key==='done'?'open':key==='doing'?'week':'watch'}">${i.student}</span><h4>${i.title}</h4><p>${i.detail}</p><footer><span>${i.date}</span>${key!=='done'?`<button class="text-button" data-advance="${i.id}">다음 단계 →</button>`:'<span>✓ 확인됨</span>'}</footer></article>`).join('')||'<p class="muted">기록이 없습니다.</p>'}</section>`}).join('')}
function openEvidence(id){const s=signals.find(x=>x.id===Number(id));$('#dialogTitle').textContent=`${s.name} · ${s.title}`;$('#dialogContent').innerHTML=`<h3>연결된 근거</h3>${s.evidence.map(e=>`<div class="evidence-box">${e}</div>`).join('')}<h3>가능한 해석</h3><div class="hypotheses">${s.hypotheses.map(h=>`<span>${h}</span>`).join('')}</div><h3>추천 관찰</h3><p>${s.observation}</p><div class="notice warning"><span>!</span><p>가능성에 대한 가설입니다. 원문 검토와 실제 관찰·대화로 확인해 주세요.</p></div>`;$('#saveObservation').dataset.signal=id;$('#evidenceDialog').showModal()}
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{const view=btn.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$('#pageTitle').textContent=pageTitles[view];if(view==='settings')renderSettings();$('#sidebar').classList.remove('open');window.scrollTo(0,0)}));
document.addEventListener('click',e=>{const evidence=e.target.closest('[data-evidence]');if(evidence)openEvidence(evidence.dataset.evidence);const closer=e.target.closest('[data-close]');if(closer)closer.closest('dialog').close();const go=e.target.closest('[data-go]');if(go)$(`.nav-item[data-view="${go.dataset.go}"]`).click();const advance=e.target.closest('[data-advance]');if(advance){const items=getObservations();const item=items.find(i=>i.id===Number(advance.dataset.advance));item.status=item.status==='todo'?'doing':'done';saveObservations(items);showToast('관찰 상태를 변경했습니다.')}const remove=e.target.closest('[data-remove-student]');if(remove){classSettings=collectSettingsForm();classSettings.students.splice(Number(remove.dataset.removeStudent),1);renderSettings();showToast('명단에서 삭제했습니다. 저장 버튼을 눌러 확정하세요.')}});
$('.filter-tabs').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;$$('.filter-tabs button').forEach(b=>b.classList.toggle('active',b===e.target));renderAnalysis(e.target.dataset.filter)});
$('#saveObservation').addEventListener('click',e=>{const s=signals.find(x=>x.id===Number(e.target.dataset.signal));const items=getObservations();items.unshift({id:Date.now(),status:'todo',student:s.name,title:s.title,detail:s.observation,date:'이번 주'});saveObservations(items);$('#evidenceDialog').close();showToast('관찰 과제로 저장했습니다.')});
$('#addObservation').addEventListener('click',()=>{const items=getObservations();items.unshift({id:Date.now(),status:'todo',student:'학생 선택',title:'새 관찰 기록',detail:'구체적인 시간·상황·행동을 기록해 주세요.',date:'날짜 미정'});saveObservations(items);showToast('새 관찰 기록을 추가했습니다.')});
$('#copyLink').addEventListener('click',event=>{navigator.clipboard?.writeText(event.currentTarget.dataset.link);showToast('참여 링크를 복사했습니다.')});
$('#refreshResponses').addEventListener('click',refreshResponses);
$('#syncRoster').addEventListener('click',syncRoster);
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#saveSettings').addEventListener('click',applySettings);
$('#classSettingsForm').addEventListener('submit',event=>{event.preventDefault();applySettings()});
$('#addStudent').addEventListener('click',()=>{classSettings=collectSettingsForm();const number=classSettings.students.length?Math.max(...classSettings.students.map(student=>student.number))+1:1;classSettings.students.push({number,name:'',accessCode:String(Math.floor(100000+Math.random()*900000))});renderSettings();const inputs=$$('[data-student-name]');inputs.at(-1)?.focus()});
$('#pasteRoster').addEventListener('click',()=>{$('#rosterPaste').value='';$('#pasteDialog').showModal()});
$('#applyRosterPaste').addEventListener('click',()=>{const parsed=$('#rosterPaste').value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const parts=line.split(/[,\t]/).map(part=>part.trim());const hasNumber=parts.length>1&&!Number.isNaN(Number(parts[0]));return{number:hasNumber?Number(parts[0]):index+1,name:hasNumber?parts.slice(1).join(' '):parts.join(' ')}}).filter(student=>student.name);if(!parsed.length){showToast('붙여넣을 학생 이름을 입력해 주세요.');return}classSettings={...collectSettingsForm(),students:parsed};renderSettings();$('#pasteDialog').close();showToast(`${parsed.length}명의 명단을 불러왔습니다. 저장 버튼을 눌러 확정하세요.`)});
$('#toggleNames').addEventListener('click',e=>{const show=$('#network').classList.toggle('show-names');e.target.textContent=show?'이름 숨기기':'이름 표시';$$('.nodes g').forEach(g=>{const original=g.querySelector('text');original.textContent=show?g.querySelector('title').textContent:original.textContent.charAt(0)})});
const steps=[`<div class="survey-question"><p class="eyebrow">나의 학교생활</p><h2>이번 달에 친구를 존중하며 이야기했나요?</h2><p>가장 가까운 답을 골라 주세요. 점수는 평가나 순위에 사용되지 않아요.</p><div class="rating-options">${[1,2,3,4,5].map((n,i)=>`<label><input type="radio" name="rating" value="${n}" ${n===4?'checked':''}><strong>${n}점</strong> · ${['거의 못했어요','조금 어려웠어요','보통이에요','잘했어요','매우 잘했어요'][i]}</label>`).join('')}</div></div>`,`<div class="survey-question"><p class="eyebrow">내 마음 표현하기</p><h2>요즘 학교생활에서 마음에 걸리는 일이 있나요?</h2><p>직접 겪은 일과 들은 일을 구분해서, 기억나는 만큼만 적어도 괜찮아요.</p><textarea placeholder="언제, 어디서, 어떤 일이 있었는지 적어 주세요."></textarea></div>`,`<div class="survey-question"><p class="eyebrow">도움 요청</p><h2>선생님의 도움이 지금 필요한가요?</h2><p>급한 도움이 필요하면 설문을 기다리지 말고 바로 선생님께 알려 주세요.</p><div class="help-choice"><label><input type="radio" name="help" checked> 지금은 괜찮아요.</label><label><input type="radio" name="help"> 이번 주에 이야기하고 싶어요.</label><label><input type="radio" name="help"> 바로 도와주세요.</label></div></div>`];let step=0;
function renderStep(){ $('#surveyStep').innerHTML=steps[step];$('#stepLabel').textContent=`${step+1} / ${steps.length}`;$('#surveyProgress').style.width=`${(step+1)/steps.length*100}%`;$('#prevStep').style.visibility=step?'visible':'hidden';$('#nextStep').textContent=step===steps.length-1?'제출하기':'다음'}
$('#openStudentSurvey').addEventListener('click',event=>{event.currentTarget.href=$('#copyLink').dataset.link});
$('#prevStep').addEventListener('click',()=>{if(step){step--;renderStep()}});$('#nextStep').addEventListener('click',()=>{if(step<steps.length-1){step++;renderStep()}else{$('#studentDialog').close();showToast('미리보기 설문이 제출되었습니다.')}});
syncSignalNames();renderClassIdentity();renderHomeSignals();renderAnalysis();renderStudents();renderObservations();renderSettings();renderParticipationLink();renderResponses([]);
