const params=new URLSearchParams(location.search);const joinToken=params.get('join')||'';let verifiedStudent=null;let peerStudents=[];let availableStudents=[];let draftTimer=null;let surveyStartedAt=0;let submissionId=crypto.randomUUID();
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const ratingItems=[['study','공부를 열심히 했습니다.','수업에 집중하고 스스로 숙제를 했어요.'],['listening','적극적으로 경청하고 함께 배웠습니다.','선생님과 친구의 말을 집중해서 들었어요.'],['respect','친구와 사이좋게 지냈습니다.','친구를 존중하고 싫다고 하면 멈추었어요.'],['manners','예의바르게 행동했습니다.','밝게 인사하고 바르고 고운 말을 사용했어요.'],['responsibility','스스로 해야 할 일을 잘했습니다.','교과서 준비, 제출, 모둠활동, 청소 등을 책임감 있게 했어요.']];
$('#classLabel').textContent='우리 반 · 월간 학교생활 돌아보기';
$('#selfRatings').innerHTML=ratingItems.map(([key,title,description])=>`<div class="rating-block"><h3>${title}</h3><p>${description}</p><div class="rating-options">${[1,2,3,4,5].map(score=>`<label><input type="radio" name="rating_${key}" value="${score}" ${score===3?'checked':''}>${score}점</label>`).join('')}</div><input class="rating-reason" id="reason_${key}" placeholder="그렇게 생각한 이유를 적어 주세요."></div>`).join('');
function relationshipLabel(name){const text=String(name||''),last=text.charCodeAt(text.length-1),hangul=last>=0xac00&&last<=0xd7a3,hasFinal=hangul&&(last-0xac00)%28!==0;return `${text}${hasFinal?'과':'와'}의 관계`}
function fillFriendOptions(students){const orderedStudents=[...students].sort((a,b)=>Number(a.number)-Number(b.number));peerStudents=orderedStudents.filter(student=>Number(student.number)!==Number(verifiedStudent.number));const positiveOptions=kind=>peerStudents.map(student=>`<label><input type="checkbox" data-positive-kind="${kind}" value="${Number(student.number)}"> <span>${Number(student.number)}번 ${student.name}</span></label>`).join('');$('#kindStudents').innerHTML=positiveOptions('kind');$('#growthStudents').innerHTML=positiveOptions('growth');$('#relationshipList').innerHTML=orderedStudents.map(student=>Number(student.number)===Number(verifiedStudent.number)?`<div class="relationship-row self-row"><span>${student.number}번 ${student.name} (나)</span><button type="button" class="self-smile" id="selfSmile" aria-pressed="false" aria-label="내 이름에 스마일 선택">☺</button></div>`:`<label class="relationship-row"><span>${student.number}번 ${student.name}</span><select data-relation-student="${student.number}" aria-label="${relationshipLabel(student.name)}"><option value="">선택</option><option value="5">5 · 아주 좋음</option><option value="4">4 · 좋음</option><option value="3">3 · 보통</option><option value="2">2 · 불편함</option><option value="1">1 · 매우 불편함</option></select></label>`).join('');$('#selfSmile').addEventListener('click',event=>{const selected=event.currentTarget.getAttribute('aria-pressed')!=='true';event.currentTarget.setAttribute('aria-pressed',String(selected));event.currentTarget.classList.toggle('selected',selected)})}
async function loadRoster(){if(!joinToken){$('#studentSelect').innerHTML='<option value="">참여 링크를 확인해 주세요</option>';$('#loginMessage').textContent='담임 선생님이 공유한 새 학생 참여 링크로 접속해 주세요.';return}try{const students=await supabaseRpc('get_roster_by_token',{p_token:joinToken});availableStudents=students;$('#studentSelect').innerHTML='<option value="">내 이름을 선택하세요</option>'+students.map(student=>`<option value="${student.number}">${student.number}번 ${student.name}</option>`).join('')}catch(error){$('#studentSelect').innerHTML='<option value="">명단을 불러오지 못했습니다</option>';$('#loginMessage').textContent=`참여 링크가 만료되었거나 명단을 불러오지 못했습니다: ${error.message}`}}
function draftKey(){return verifiedStudent?`ieum-student-draft:${joinToken}:${verifiedStudent.number}`:''}
function restoreDraft(){const key=draftKey();if(!key)return;try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(!saved||Date.now()-saved.savedAt>12*60*60*1000){sessionStorage.removeItem(key);return}const payload=saved.payload||{};submissionId=payload.submissionId||submissionId;Object.entries(payload.selfRatings||{}).forEach(([name,value])=>{const radio=$(`input[name="rating_${name}"][value="${Number(value.score)}"]`);if(radio)radio.checked=true;const reason=$(`#reason_${name}`);if(reason)reason.value=value.reason||''});const fields={kindDetail:payload.peerObservations?.kind?.detail,growthDetail:payload.peerObservations?.growth?.detail,hurtDetail:payload.peerObservations?.hurt?.detail,helpDetail:payload.peerObservations?.needsHelp?.detail,worryDetail:payload.studentState?.worryDetail,teacherWish:payload.studentState?.teacherWish,parentWish:payload.studentState?.parentWish,unresolvedDetail:payload.unresolved?.detail};Object.entries(fields).forEach(([id,value])=>{if($(`#${id}`))$(`#${id}`).value=value||''});['kind','growth'].forEach(kind=>(payload.peerObservations?.[kind]?.studentNumbers||[]).forEach(number=>{const input=$(`[data-positive-kind="${kind}"][value="${Number(number)}"]`);if(input)input.checked=true}));if($('#sourceType'))$('#sourceType').value=payload.peerObservations?.hurt?.sourceType||'';if($('#frequency'))$('#frequency').value=payload.peerObservations?.hurt?.frequency||'';if($('#ongoing'))$('#ongoing').checked=!!payload.peerObservations?.hurt?.ongoing;if($('#selfSmile')){$('#selfSmile').setAttribute('aria-pressed',String(!!payload.selfSmile));$('#selfSmile').classList.toggle('selected',!!payload.selfSmile)};(payload.relationships||[]).forEach(row=>{const select=$(`[data-relation-student="${row.targetNumber}"]`);if(select)select.value=String(row.score)});const help=$(`input[name="helpNow"][value="${payload.helpNow}"]`);if(help)help.checked=true;$('#draftStatus').textContent='이 탭에 임시 저장된 작성 내용을 복구했습니다.'}catch(error){sessionStorage.removeItem(key)}}
function submissionPayload(){return{...collectPayload(),submissionId}}
function saveDraft(){if(!verifiedStudent)return;try{sessionStorage.setItem(draftKey(),JSON.stringify({savedAt:Date.now(),payload:submissionPayload()}));$('#draftStatus').textContent=`이 탭에 임시 저장됨 · ${new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`}catch(error){$('#draftStatus').textContent='임시 저장을 사용할 수 없습니다. 제출 전 탭을 닫지 마세요.'}}
function verifyStudent(){const number=Number($('#studentSelect').value);const student=availableStudents.find(item=>Number(item.number)===number);if(!student){$('#loginMessage').textContent='내 이름을 선택해 주세요.';return}verifiedStudent=student;surveyStartedAt=Date.now();fillFriendOptions(availableStudents);$('#studentGreeting').textContent=`${verifiedStudent.name} 학생, 안녕하세요`;$('#loginCard').hidden=true;$('#surveyForm').hidden=false;restoreDraft();window.scrollTo(0,0)}
$('#verifyStudent').addEventListener('click',verifyStudent);
function selectedName(id){const option=$(`#${id}`).selectedOptions[0];return option?.value?option.textContent.replace(/^\d+번\s*/,''):''}
function collectPayload(){const selfRatings={};ratingItems.forEach(([key])=>{selfRatings[key]={score:Number($(`input[name="rating_${key}"]:checked`).value),reason:$(`#reason_${key}`).value.trim()}});return{action:'submit',studentNumber:verifiedStudent.number,studentName:verifiedStudent.name,surveyMonth:new Date().toISOString().slice(0,7),submittedAt:new Date().toISOString(),completionSeconds:surveyStartedAt?Math.max(1,Math.round((Date.now()-surveyStartedAt)/1000)):null,selfRatings,peerObservations:{kind:{studentNumbers:$$('[data-positive-kind="kind"]:checked').map(input=>Number(input.value)),detail:$('#kindDetail').value.trim()},growth:{studentNumbers:$$('[data-positive-kind="growth"]:checked').map(input=>Number(input.value)),detail:$('#growthDetail').value.trim()},hurt:{detail:$('#hurtDetail').value.trim(),sourceType:$('#sourceType').value,frequency:$('#frequency').value,ongoing:$('#ongoing').checked},needsHelp:{detail:$('#helpDetail').value.trim()}},studentState:{worryDetail:$('#worryDetail').value.trim(),teacherWish:$('#teacherWish').value.trim(),parentWish:$('#parentWish').value.trim()},selfSmile:$('#selfSmile')?.getAttribute('aria-pressed')==='true',relationships:$$('[data-relation-student]').filter(select=>select.value).map(select=>({targetNumber:Number(select.dataset.relationStudent),score:Number(select.value)})),unresolved:{detail:$('#unresolvedDetail').value.trim()},helpNow:$('input[name="helpNow"]:checked').value}}
$('#surveyForm').addEventListener('input',()=>{clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,500)});document.addEventListener('click',event=>{if(event.target.closest('#selfSmile'))setTimeout(saveDraft,0)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&verifiedStudent)saveDraft()});window.addEventListener('pagehide',()=>{if(verifiedStudent)saveDraft()});window.addEventListener('online',()=>{if(!availableStudents.length&&!verifiedStudent){$('#loginMessage').textContent='인터넷에 다시 연결되어 명단을 불러오고 있습니다.';loadRoster();return}$('#submitMessage').textContent='인터넷에 다시 연결되었습니다. 작성 내용은 그대로 유지됩니다.'});window.addEventListener('offline',()=>{if(!verifiedStudent){$('#loginMessage').textContent='인터넷 연결이 끊겼습니다. 연결되면 명단을 다시 불러옵니다.';return}$('#submitMessage').textContent='인터넷 연결이 끊겼습니다. 이 탭의 임시 저장 내용을 유지합니다.'});
$('#surveyForm').addEventListener('submit',async event=>{event.preventDefault();if(!verifiedStudent)return;const button=$('#submitSurvey');button.disabled=true;$('#submitMessage').textContent='응답을 안전하게 DB에 저장하고 있어요…';const payload=submissionPayload();try{await supabaseRpc('submit_response_by_token',{p_token:joinToken,p_student_number:verifiedStudent.number,p_student_name:verifiedStudent.name,p_payload:payload});sessionStorage.removeItem(draftKey());$('#surveyForm').hidden=true;$('#completeCard').hidden=false;window.scrollTo(0,0)}catch(error){saveDraft();$('#submitMessage').textContent=`제출하지 못했습니다. 작성 내용은 이 탭에 보관했습니다: ${error.message}`;button.disabled=false}});
loadRoster();
