const params=new URLSearchParams(location.search);const classId=params.get('class')||'2026-5-2';let verifiedStudent=null;let peerStudents=[];let availableStudents=[];
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const ratingItems=[['study','공부를 열심히 했습니다.','수업에 집중하고 스스로 숙제를 했어요.'],['listening','적극적으로 경청하고 함께 배웠습니다.','선생님과 친구의 말을 집중해서 들었어요.'],['respect','친구와 사이좋게 지냈습니다.','친구를 존중하고 싫다고 하면 멈추었어요.'],['manners','예의바르게 행동했습니다.','밝게 인사하고 바르고 고운 말을 사용했어요.'],['responsibility','스스로 해야 할 일을 잘했습니다.','교과서 준비, 제출, 모둠활동, 청소 등을 책임감 있게 했어요.']];
$('#classLabel').textContent=`${classId} · 월간 학교생활 돌아보기`;
$('#selfRatings').innerHTML=ratingItems.map(([key,title,description])=>`<div class="rating-block"><h3>${title}</h3><p>${description}</p><div class="rating-options">${[1,2,3,4,5].map(score=>`<label><input type="radio" name="rating_${key}" value="${score}" ${score===3?'checked':''}>${score}점</label>`).join('')}</div><input class="rating-reason" id="reason_${key}" placeholder="그렇게 생각한 이유를 적어 주세요."></div>`).join('');
function localSettings(){try{const saved=JSON.parse(localStorage.getItem('ieum-class-settings'));if(saved?.students?.length)return{...saved,students:saved.students.map((student,index)=>({...student,accessCode:student.accessCode||String(731204+index*7919).slice(-6)}))}}catch(error){}const names=Array.from({length:28},(_,index)=>`학생${String(index+1).padStart(2,'0')}`);return{students:names.map((name,index)=>({number:index+1,name,accessCode:String(731204+index*7919).slice(-6)}))}}
function fillFriendOptions(students){const orderedStudents=[...students].sort((a,b)=>Number(a.number)-Number(b.number));peerStudents=orderedStudents.filter(student=>Number(student.number)!==Number(verifiedStudent.number));$('#relationshipList').innerHTML=orderedStudents.map(student=>Number(student.number)===Number(verifiedStudent.number)?`<div class="relationship-row self-row"><span>${student.number}번 ${student.name} (나)</span><button type="button" class="self-smile" id="selfSmile" aria-pressed="false" aria-label="내 이름에 스마일 선택">☺</button></div>`:`<label class="relationship-row"><span>${student.number}번 ${student.name}</span><select data-relation-student="${student.number}" aria-label="${student.name}과의 관계"><option value="">선택</option><option value="5">5 · 아주 좋음</option><option value="4">4 · 좋음</option><option value="3">3 · 보통</option><option value="2">2 · 불편함</option><option value="1">1 · 매우 불편함</option></select></label>`).join('');$('#selfSmile').addEventListener('click',event=>{const selected=event.currentTarget.getAttribute('aria-pressed')!=='true';event.currentTarget.setAttribute('aria-pressed',String(selected));event.currentTarget.classList.toggle('selected',selected)})}
async function loadRoster(){try{const students=await supabaseRpc('get_roster',{p_class_id:classId});availableStudents=students;$('#studentSelect').innerHTML='<option value="">내 이름을 선택하세요</option>'+students.map(student=>`<option value="${student.number}">${student.number}번 ${student.name}</option>`).join('')}catch(error){$('#studentSelect').innerHTML='<option value="">명단을 불러오지 못했습니다</option>';$('#loginMessage').textContent=`DB 명단을 불러오지 못했습니다: ${error.message}`}}
function verifyStudent(){const number=Number($('#studentSelect').value);const student=availableStudents.find(item=>Number(item.number)===number);if(!student){$('#loginMessage').textContent='내 이름을 선택해 주세요.';return}verifiedStudent=student;fillFriendOptions(availableStudents);$('#studentGreeting').textContent=`${verifiedStudent.name} 학생, 안녕하세요`;$('#loginCard').hidden=true;$('#surveyForm').hidden=false;window.scrollTo(0,0)}
$('#verifyStudent').addEventListener('click',verifyStudent);
function selectedName(id){const option=$(`#${id}`).selectedOptions[0];return option?.value?option.textContent.replace(/^\d+번\s*/,''):''}
function collectPayload(){const selfRatings={};ratingItems.forEach(([key])=>{selfRatings[key]={score:Number($(`input[name="rating_${key}"]:checked`).value),reason:$(`#reason_${key}`).value.trim()}});return{action:'submit',classId,studentNumber:verifiedStudent.number,studentName:verifiedStudent.name,surveyMonth:new Date().toISOString().slice(0,7),submittedAt:new Date().toISOString(),selfRatings,peerObservations:{kind:{detail:$('#kindDetail').value.trim()},growth:{detail:$('#growthDetail').value.trim()},hurt:{detail:$('#hurtDetail').value.trim(),sourceType:$('#sourceType').value,frequency:$('#frequency').value,ongoing:$('#ongoing').checked},needsHelp:{detail:$('#helpDetail').value.trim()}},studentState:{worryDetail:$('#worryDetail').value.trim(),teacherWish:$('#teacherWish').value.trim(),parentWish:$('#parentWish').value.trim()},selfSmile:$('#selfSmile')?.getAttribute('aria-pressed')==='true',relationships:$$('[data-relation-student]').filter(select=>select.value).map(select=>({targetNumber:Number(select.dataset.relationStudent),score:Number(select.value)})),unresolved:{detail:$('#unresolvedDetail').value.trim()},helpNow:$('input[name="helpNow"]:checked').value}}
$('#surveyForm').addEventListener('submit',async event=>{event.preventDefault();if(!verifiedStudent)return;const button=$('#submitSurvey');button.disabled=true;$('#submitMessage').textContent='응답을 안전하게 DB에 저장하고 있어요…';const payload=collectPayload();try{await supabaseRpc('submit_response',{p_class_id:classId,p_student_number:verifiedStudent.number,p_student_name:verifiedStudent.name,p_payload:payload});$('#surveyForm').hidden=true;$('#completeCard').hidden=false;window.scrollTo(0,0)}catch(error){$('#submitMessage').textContent=`제출하지 못했습니다: ${error.message}`;button.disabled=false}});
loadRoster();
