const test=require('node:test'),assert=require('node:assert/strict');
const {compare}=require('../relationship-changes.js'),data=require('../supabase/functions/analyze-class/relationship-data.js');
const students=[1,2].map(number=>({number,studentId:`s${number}`}));
function fixture(oldScore=3,newScore=5){return ['2026-06','2026-07'].flatMap((month,index)=>students.map(student=>({id:`${month}-${student.number}`,student_id:student.studentId,student_number:student.number,survey_month:`${month}-01`,submitted_at:`${month}-15T00:00:00Z`,payload_json:{relationships:[{targetNumber:3-student.number,score:index?newScore:oldScore}]}})))}
const run=rows=>compare(rows,students,'2026-07',data);
test('transfer month does not imply relationship loss',()=>{const roster=students.map(student=>({...student,transferredOn:student.number===1?'2026-07-10':null}));const result=compare(fixture(5,3),roster,'2026-07',data);assert.equal(result.pairs[0].state,'enrollment');assert.equal(result.total.below.length,0);assert.equal(result.total.enrollment.length,1)});
test('four comparable observations distinguish threshold changes without mutating rows',()=>{for(const [oldScore,newScore,state] of [[3,5,'new'],[5,5,'continued'],[5,3,'below'],[3,3,'other']]){const rows=fixture(oldScore,newScore),original=JSON.stringify(rows);assert.equal(run(rows).pairs[0].state,state);assert.equal(run(rows).total.comparable,1);assert.equal(JSON.stringify(rows),original)}});
test('missing rows and one-way answers defer comparison',()=>{const rows=fixture();assert.equal(run(rows.slice(1)).pairs[0].state,'missing');rows[0].payload_json.relationships=[];assert.equal(run(rows).pairs[0].state,'missing')});
test('missing, different or renumbered identities defer comparison',()=>{for(const variant of ['missing','different','renumbered']){const rows=fixture();if(variant==='missing')delete rows[0].student_id;if(variant==='different')rows[0].student_id='another';if(variant==='renumbered')rows[0].payload_json.studentNumber=9;assert.equal(run(rows).pairs[0].state,'identity')}});
test('comparison does not bridge missing calendar months',()=>{const result=compare(fixture(),students,'2026-09',data);assert.equal(result.previousMonth,'2026-08');assert.equal(result.hasPrevious,false);assert.equal(result.total.comparable,0);assert.equal(compare([],students,'2027-01',data).previousMonth,'2026-12');assert.equal(compare([],students,'invalid',data),null)});
test('latest valid response and exclusions follow shared normalization',()=>{const rows=fixture();rows.push({...rows[0],id:'new',submitted_at:'2026-06-20T00:00:00Z',payload_json:{relationships:[]}});assert.equal(run(rows).pairs[0].state,'missing');rows.at(-1).analysis_excluded=true;assert.equal(run(rows).pairs[0].state,'new');rows[0].deleted_at='2026-08-01';assert.equal(run(rows).pairs[0].state,'missing')});
test('outsiders do not increase pair counts',()=>{const rows=fixture();rows.push({...rows[0],student_number:99,student_id:'outsider'});assert.equal(run(rows).pairs.length,1);assert.equal(run(rows).byStudent.get(1).new[0].b,2)});
