const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
const data=require('../supabase/functions/analyze-class/relationship-data.js');
const studentId='11111111-1111-4111-8111-111111111111',otherId='22222222-2222-4222-8222-222222222222';
const makeContext=()=>({student:{studentId,number:1,name:'가상학생가'},roster:[{number:1,name:'가상학생가'},{number:2,name:'가상학생나'}],responses:[{id:'own',student_id:studentId,student_number:1,survey_month:'2026-09-01',submitted_at:'2026-09-02T00:00:00Z',payload_json:{studentState:{worryDetail:'가상학생나와 발표 연습을 하고 싶어요. test@example.invalid 010-1234-5678'},relationships:[]}},{id:'other',student_id:otherId,student_number:2,survey_month:'2026-09-01',submitted_at:'2026-09-02T00:00:00Z',payload_json:{studentState:{worryDetail:'관련 없는 다른 학생의 비공개 고민'},relationships:[{targetNumber:1,score:1},{targetNumber:1,score:5}]}}],observations:[],sourceHash:'source-v1',card:null,feedback:[],remaining:10});
const validCard=()=>({summary:{text:'발표 경험을 먼저 확인해 보세요.',refs:['E1']},strengths:[],needs:[],question:{text:'발표할 때 어떤 도움이 있으면 좋겠니?',refs:['E1']},actions:[{title:'짝과 먼저 연습하기',steps:['편안한 짝과 먼저 이야기할 시간을 주세요.'],refs:['E1']}],check_after:'말하기가 조금 더 편해졌는지 물어보세요.',limitations:['현재 자료만으로 원인을 확정할 수 없습니다.']});
async function harness({action='load',authorized=true,context=makeContext(),output=validCard(),apiStatus=200,apiError=null,denied=false,key=true,force=false}={}){
  const {coachingApiError}=await import('../supabase/functions/student-coaching/api-errors.mjs');const api=await import('../supabase/functions/student-coaching/coaching.mjs'),{redactStudentNames}=await import('../supabase/functions/analyze-class/privacy.mjs');let handler,aiBody;const calls=[],saved=[];
  const fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):{};calls.push(url);
    if(url.endsWith('/auth/v1/user'))return Response.json(authorized?{id:'teacher'}:{},{status:authorized?200:401});
    if(url.endsWith('/rpc/teacher_get_student_coaching_context_auth'))return Response.json(denied?{message:'담당 학급에 대한 권한이 없습니다.'}:context,{status:denied?403:200});
    if(url.endsWith('/rpc/teacher_begin_student_coaching_auth'))return Response.json('run-id');
    if(url.endsWith('/rpc/teacher_finish_student_coaching_auth')){saved.push(body);return Response.json(true)}
    if(url==='https://api.openai.com/v1/responses'){aiBody=body;return Response.json({error:apiError,status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(output)}]}]},{status:apiStatus})}
    throw Error('Unexpected mock request');
  };
  const source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/student-coaching/index.ts','utf8').replace(/^import .*;\r?\n/gm,''));
  vm.runInNewContext(source,{...api,coachingApiError,Error,IeumRelationshipData:data,redactStudentNames,Response,Request,AbortSignal,fetch,Deno:{env:{get:name=>name==='SUPABASE_URL'?'https://mock.invalid':name==='OPENAI_API_KEY'&&!key?undefined:'test-only'},serve:fn=>handler=fn}});
  const response=await handler(new Request('https://mock.invalid/coaching',{method:'POST',headers:{Authorization:'Bearer test-only'},body:JSON.stringify({classId:'fixture',studentId,action,force})}));return{status:response.status,result:await response.json(),calls,aiBody,saved};
}
test('학생 코칭 근거는 선택 학생 자료와 계산값만 포함한다',async()=>{const api=await import('../supabase/functions/student-coaching/coaching.mjs'),result=api.buildEvidence(makeContext(),data);assert.equal(result.sources.length,2);assert.match(result.sources[1].value,/평균 5.00점/);assert.doesNotMatch(JSON.stringify(result.sources),/관련 없는/);assert.equal(result.limited,true)});
test('모든 근거 필드는 현재 요청의 ID만 허용하며 요청끼리 섞이지 않는다',async()=>{const {schemaForEvidence,schema}=await import('../supabase/functions/student-coaching/coaching.mjs');const check=(value,ids)=>{const p=value.properties;for(const refs of [p.summary.properties.refs,p.strengths.items.properties.refs,p.needs.items.properties.refs,p.question.properties.refs,p.actions.items.properties.refs]){assert.deepEqual(refs.items.enum,ids);assert.equal(refs.minItems,1);assert.equal(refs.maxItems,3)}};const first=schemaForEvidence([{id:'E1'},{id:'E2'}]);check(first,['E1','E2']);check(schemaForEvidence([{id:'E9'}]),['E9']);check(first,['E1','E2']);assert.equal(schema.properties.summary.properties.refs.items.enum,undefined);assert.throws(()=>schemaForEvidence([]),/근거/)});
test('실제 API 요청 스키마의 근거 목록은 전송한 근거 목록과 일치한다',async()=>{const result=await harness({action:'generate'});const input=JSON.parse(result.aiBody.input),ids=input.evidence.map(row=>row.id);assert.deepEqual(result.aiBody.text.format.schema.properties.summary.properties.refs.items.enum,ids);assert.deepEqual(result.aiBody.text.format.schema.properties.actions.items.properties.refs.items.enum,ids);assert.equal(result.aiBody.text.format.strict,true)});
test('가명 처리로 근거 ID가 바뀌지 않는다',async()=>{const context=makeContext();context.roster.push({number:3,name:'E1'});const result=await harness({action:'generate',context});assert.equal(JSON.parse(result.aiBody.input).evidence[0].id,'E1');assert.equal(result.status,200)});
test('다섯 번째 과거 설문은 코칭 서술 근거에서 제외한다',async()=>{const api=await import('../supabase/functions/student-coaching/coaching.mjs'),context=makeContext();context.responses=Array.from({length:5},(_,i)=>({...context.responses[0],id:`own-${i}`,survey_month:`2026-0${9-i}-01`,payload_json:{studentState:{worryDetail:`가상 고민 ${i}`}}}));const result=api.buildEvidence(context,data);assert.equal(result.sources.length,4);assert.equal(result.sources.some(row=>row.responseId==='own-4'),false);assert.equal(result.sources[0].month,'2026-09')});
test('전출월에는 관계 점수를 사용하지 않고 이후 응답은 제외한다',async()=>{const api=await import('../supabase/functions/student-coaching/coaching.mjs'),context=makeContext();context.student.transferredOn='2026-09-05';assert.equal(api.buildEvidence(context,data).sources.length,1);context.student.transferredOn='2026-08-05';assert.equal(api.buildEvidence(context,data).canGenerate,false)});
test('단순 괜찮음 응답만으로는 AI 코칭을 생성하지 않는다',async()=>{const api=await import('../supabase/functions/student-coaching/coaching.mjs'),context=makeContext();context.responses=[{...context.responses[0],payload_json:{helpNow:'괜찮아요'}}];assert.equal(api.buildEvidence(context,data).canGenerate,false)});
test('없는 근거 ID와 영어 출력은 저장 전 거부한다',async()=>{const api=await import('../supabase/functions/student-coaching/coaching.mjs'),value=validCard();value.summary.refs=['UNKNOWN'];assert.throws(()=>api.validateCard(value,[{id:'E1'}]),/근거/);value.summary.refs=['E1'];value.summary.text='The student needs support';assert.throws(()=>api.validateCard(value,[{id:'E1'}]),/표현/)});
test('조회는 API 키 없이 가능하며 AI 호출을 하지 않는다',async()=>{const result=await harness({key:false});assert.equal(result.status,200);assert.equal(result.aiBody,undefined);assert.equal(result.result.canGenerate,true)});
test('자료가 바뀐 저장 카드는 숨기고 갱신 안내만 반환한다',async()=>{const context=makeContext();context.card={id:'saved',source_hash:'old',result_json:{...validCard(),version:'old'}};const result=await harness({context});assert.equal(result.result.stale,true);assert.equal(result.result.card,null);assert.equal(result.aiBody,undefined)});
test('현재 자료의 저장 카드는 생성 요청에서도 명시적 갱신 없이는 재사용한다',async()=>{const context=makeContext();context.card={id:'saved',source_hash:context.sourceHash,result_json:{...validCard(),version:'2026.09.12-student-survey-only-v2'}};const result=await harness({context,action:'generate'});assert.equal(result.status,200);assert.equal(result.result.card.id,'saved');assert.equal(result.result.cached,true);assert.equal(result.aiBody,undefined);assert.equal(result.saved.length,0)});
test('저장 카드의 근거가 깨진 경우에도 결과를 숨긴다',async()=>{const context=makeContext();context.card={id:'saved',source_hash:context.sourceHash,result_json:{...validCard(),version:'2026.09.12-student-survey-only-v2'}};context.card.result_json.summary.refs=['E999'];const result=await harness({context});assert.equal(result.result.stale,true);assert.equal(result.result.card,null)});
test('생성은 가명·연락처 가림과 store:false를 사용하고 결과를 저장한다',async()=>{const result=await harness({action:'generate'});assert.equal(result.status,200);assert.equal(result.aiBody.model,'gpt-5.6-terra');assert.equal(result.aiBody.store,false);assert.doesNotMatch(result.aiBody.input,/가상학생가|가상학생나|test@example|010-1234|관련 없는/);assert.equal(result.saved[0].p_success,true);assert.equal(result.result.card.result.version,'2026.09.12-student-survey-only-v2')});
test('잘못된 근거 결과는 실패 처리하며 저장하지 않는다',async()=>{const output=validCard();output.actions[0].refs=['E999'];const result=await harness({action:'generate',output});assert.equal(result.status,500);assert.equal(result.saved.length,1);assert.equal(result.saved[0].p_success,false)});
test('인증·학급 권한 실패는 AI 호출 전에 차단한다',async()=>{for(const options of [{authorized:false},{denied:true}]){const result=await harness({...options,action:'generate'});assert.ok([401,403].includes(result.status));assert.equal(result.aiBody,undefined);assert.equal(result.saved.length,0)}});
test('자료 없음과 API 실패를 구분하고 실패 실행을 닫는다',async()=>{const context=makeContext();context.responses=[];const empty=await harness({action:'generate',context});assert.equal(empty.status,422);assert.equal(empty.aiBody,undefined);const failure=await harness({action:'generate',apiStatus:429});assert.equal(failure.saved[0].p_success,false);assert.match(failure.result.error,/한도/)});
test('API 잔액 부족과 일시 제한을 구분하고 원문 오류를 노출하지 않는다',async()=>{for(const [code,expected] of [['insufficient_quota',/잔액/],['rate_limit_exceeded',/일시적인 요청량/],['unknown',/구분할 수 없습니다/]]){const result=await harness({action:'generate',apiStatus:429,apiError:{code,message:'sensitive-account-detail'}});assert.match(result.result.error,expected);assert.doesNotMatch(result.result.error,/sensitive-account-detail/);assert.equal(result.saved[0].p_success,false);assert.equal(result.calls.filter(url=>url.includes('api.openai.com')).length,1)}});
test('교사 관찰·면담·적용 결과는 근거와 외부 AI 요청에서 제외한다',async()=>{
  const context=makeContext();context.observations=[{id:'old',survey_month:'2026-09-01',observed_fact:'PRIVATE_OBSERVATION',interview_note:'PRIVATE_INTERVIEW'}];context.feedback=[{status:'helpful',note:'PRIVATE_FEEDBACK'}];
  const result=await harness({action:'generate',context});assert.equal(result.status,200);assert.doesNotMatch(result.aiBody.input,/PRIVATE_|prior_feedback|observation/);assert.ok(result.result.sources.every(row=>row.kind!=='observation'));
  context.responses=[];const empty=await harness({action:'generate',context});assert.equal(empty.status,422);assert.equal(empty.aiBody,undefined);
});
test('설문 전용 이전 버전은 자료 해시가 같아도 조회 시 숨기며 AI를 호출하지 않는다',async()=>{
 const context=makeContext();context.card={id:'legacy',source_hash:context.sourceHash,result_json:{...validCard(),version:'2026.09.09-student-coaching-v1'}};
 const result=await harness({context});assert.equal(result.result.card,null);assert.equal(result.result.stale,true);assert.equal(result.aiBody,undefined);assert.equal(result.saved.length,0);
});
