const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('student-coaching-pdf.js','utf8');
const item={text:'가상 코칭 <script>',refs:['E1']};
const data={card:{id:'card',result:{summary:item,question:item,actions:[{title:'연습하기',steps:['한 문장 말하기'],refs:['E1']}],check_after:'다시 확인',strengths:[item],needs:[],limitations:['단정하지 않기']},basisMonth:'2026-09'},sources:[{id:'E1',label:'고민',month:'2026-09',type:'학생 응답',value:'원문 비밀'}],feedback:[{card_id:'other',note:'다른 학생 비밀'},{card_id:'card',status:'helpful',note:'교사 기록',created_at:'2026-09-11'}]};
function context(extra={}){return vm.createContext({escapeHTML:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),...extra})}
function render(value,options){const ctx=context();vm.runInContext(code,ctx);return ctx.buildStudentCoachingPdfSection(value,options)}
test('코칭 PDF는 핵심 내용·연결 근거·현재 카드 적용 결과를 표시하고 HTML을 이스케이프한다',()=>{const html=render(data);for(const title of ['이번 코칭의 초점','학생에게 건넬 말','교사가 해볼 일','다음에 확인할 점','교사의 적용 결과','근거 [1]'])assert.ok(html.includes(title));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('교사 기록'));assert.ok(!html.includes('다른 학생 비밀'));assert.ok(!html.includes('원문 비밀'));assert.ok(render(data,{includeOriginals:true}).includes('원문 비밀'))});
test('이름 제외·오래된 카드·없는 카드는 코칭과 교사 기록을 출력하지 않는다',()=>{for(const html of [render(data,{includeNames:false}),render({...data,stale:true}),render(null)]){assert.ok(!html.includes('가상 코칭'));assert.ok(!html.includes('교사 기록'))}});
test('학생용 간결 PDF는 교사 적용 기록과 관찰 근거 라벨을 제외한다',()=>{const html=render({...data,sources:[{id:'E1',kind:'observation',type:'교사 관찰',label:'교사 관찰 사실',month:'2026-09'}]},{compact:true});assert.ok(html.includes('학생 코칭'));assert.ok(html.includes('이번 코칭의 초점'));assert.ok(!html.includes('교사의 적용 결과'));assert.ok(!html.includes('교사 기록'));assert.ok(!html.includes('교사 관찰 사실'))});
test('PDF 조회는 load만 요청하고 세션 변경 시 중단한다',async()=>{const calls=[];const ctx=context({studentCoachingEpoch:1,classSettings:{classId:'class'},getTeacherSession:()=>true,teacherEdgeFunction:async(name,body)=>{calls.push(body);return data}});vm.runInContext(code,ctx);await ctx.loadStudentCoachingPdfSection({studentId:'student'},{includeNames:true});assert.equal(calls[0].action,'load');assert.equal(calls.length,1);ctx.teacherEdgeFunction=async()=>{ctx.studentCoachingEpoch++;return data};await assert.rejects(()=>ctx.loadStudentCoachingPdfSection({studentId:'student'},{includeNames:true}),/변경/)});
